---
# yaml-language-server: $schema=https://json.schemastore.org/github-action.json
name: App Tests
description: Takes an app, app image and token then runs app tests

inputs:
  app:
    description: App Name
    required: true
  image:
    description: Image
    required: true
  token:
    description: GitHub Token
    required: true

runs:
  using: composite
  steps:
    - name: Setup Actions Script Path
      shell: bash
      run: |- # zizmor: ignore[github-env]
        echo "${{ github.action_path }}" >> $GITHUB_PATH

    - name: Setup Testing Tools
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
        APP: ${{ inputs.app }}
      run: |-
        setup.sh "${APP}"

    - name: Run Tests
      shell: bash
      env:
        APP: ${{ inputs.app }}
        IMAGE: ${{ inputs.image }}
      run: |-
        run.sh "${APP}" "${IMAGE}"
