---
# yaml-language-server: $schema=https://json.schemastore.org/github-action.json
name: Definitive Versions
description: Takes a version string and returns the definitive versions

inputs:
  version:
    description: Version
    required: true

outputs:
  is-valid-semver:
    description: If version is valid semantic versioning
    value: ${{ steps.version.outputs.is-valid-semver }}
  semantic:
    description: Semantic Version
    value: ${{ steps.version.outputs.semantic }}
  raw:
    description: Raw Version
    value: ${{ steps.version.outputs.raw }}

runs:
  using: composite
  steps:
    - name: Setup Node
      uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
      with:
        node-version: 22.x

    - name: Install Semver
      shell: bash
      run: npm install semver

    - name: Determine Definitive Version
      uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
      id: version
      with:
        script: |
          const semver = require('semver');

          // Strip the v prefix and pre-release info
          function sanitize(version) {
              return version.replace(/^v/, '').split('-')[0];
          }

          function calver() {
              const now = new Date();
              return `${now.getFullYear()}.${now.getMonth() + 1}.${now.getDate()}`;
          }

          const version = '${{ inputs.version }}';
          const strictSemverRegex = /^v?(\d+(\.\d+)?(\.\d+)?)/;

          const parsedVersion = strictSemverRegex.exec(version);
          const isValidSemver = parsedVersion !== null;
          const parsedSemver = isValidSemver ? semver.coerce(parsedVersion[0]) : null;
          const semanticVersion = isValidSemver ? `${parsedSemver.major}.${parsedSemver.minor}.${parsedSemver.patch}` : calver();
          const rawVersion = isValidSemver ? sanitize(version) : version;

          core.setOutput('is-valid-semver', isValidSemver);
          core.setOutput('semantic', semanticVersion);
          core.setOutput('raw', rawVersion);
