[tools]
"aqua:casey/just" = "1.49.0"
"aqua:cli/cli" = "2.89.0"
"aqua:jqlang/jq" = "1.7.1"
"aqua:mikefarah/yq" = "4.52.5"
"go" = "1.26.2"

[hooks]
postinstall = [
  "mkdir -p {{config_root}}/.cache",
]
