---
version: "3"

vars:
  DEFAULT_REGISTRY: ghcr.io/bjw-s

includes:
  container:
    dir: .taskfiles/container
    taskfile: .taskfiles/container

tasks:
  default:
    silent: true
    cmds:
      - task -l
