---
version: "3"

tasks:
  build:
    desc: Build container image [APP=required] [REGISTRY={{.DEFAULT_REGISTRY}}]
    silent: true
    vars:
      # User vars
      APP: "{{ .APP }}"
      REGISTRY: "{{ .REGISTRY | default .DEFAULT_REGISTRY }}"

      # Helper vars
      APP_FOLDER: "{{ .ROOT_DIR }}/apps/{{ .APP }}"
      DOCKERFILE: "{{ .APP_FOLDER }}/Dockerfile"
      METADATA_FILE: "{{ .APP_FOLDER }}/metadata.yaml"
      APP_VERSION:
        sh: >-
          [ ! -f "{{ .METADATA_FILE }}" ] || yq -r .version "{{ .METADATA_FILE }}"
      SINGLE_PLATFORM: "linux/{{ARCH}}"
    requires:
      vars:
        - APP
    preconditions:
      - test -f "{{ .DOCKERFILE }}"
      - test -f "{{ .METADATA_FILE }}"
    cmd: >-
      docker buildx build
      --tag {{ .REGISTRY }}/{{ .APP }}:{{ .APP_VERSION }}
      --build-arg VERSION={{ .APP_VERSION }}
      --platform {{ .SINGLE_PLATFORM }}
      --file {{ .DOCKERFILE }}
      --load
      {{ .APP_FOLDER }}
