---
# yaml-language-server: $schema=https://json.schemastore.org/github-action.json
name: App Size Diff
description: Creates a Markdown summary of the size difference between two app versions

inputs:
  from-app:
    description: Baseline app image for size comparison
    required: true
  to-app:
    description: App image to be compared to the baseline
    required: true

outputs:
  size-diff-markdown:
    description: Markdown formatted output of app size comparison
    value: ${{ steps.size-diff.outputs.markdown }}

runs:
  using: composite
  steps:
    - name: Create package.json
      shell: bash
      run: |-
        cat > package.json << 'EOF'
        {
          "dependencies": {
            "execa": "^9.6.0",
            "filesize": "^11.0.2",
            "lodash": "^4.0.0",
            "markdown-table": "^3.0.4"
          }
        }
        EOF

    - name: Setup Node
      uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
      with:
        cache: npm
        cache-dependency-path: package.json
        node-version: 22.x

    - name: Setup Node Dependencies
      shell: bash
      run: |-
        npm install

    - name: App Size Diff
      uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
      id: size-diff
      env:
        FROM_APP: ${{ inputs.from-app }}
        TO_APP: ${{ inputs.to-app }}
      with:
        script: |-
          const { execaSync } = require("execa");
          const { filesize } = require("filesize");
          const { markdownTable } = require("markdown-table");
          const _ = require("lodash");

          const fromApp = process.env.FROM_APP;
          const toApp = process.env.TO_APP;

          async function getSizes(app) {
              try {
                  const { stdout } = execaSync("docker", ["manifest", "inspect", "-v", app]);
                  const manifests = _.castArray(JSON.parse(stdout.trim()));

                  return _(manifests)
                      .map(m => {
                          const platform = _.get(m, 'Descriptor.platform', {});

                          const key = _.compact([
                              platform.os,
                              platform.architecture,
                              platform.variant,
                              platform["os.version"]
                          ])
                          .join("/");

                          const layers = _.get(m, 'OCIManifest.layers') || _.get(m, 'layers', []);
                          const total = _.sumBy(layers, 'size');

                          return [key, total];
                      })
                      .fromPairs()
                      .value();
              } catch (e) {
                  core.error(`Failed to inspect ${app}: ${e.message}`);
                  return {};
              }
          }

          const fromSizes = await getSizes(fromApp);
          const toSizes   = await getSizes(toApp);

          const platforms = _(fromSizes)
              .keys()
              .union(_.keys(toSizes))
              .filter(platform => platform && !platform.includes("unknown"))
              .sort()
              .value();

          const platformRow = (platform) => {
              const previous = _.get(fromSizes, platform, 0);
              const current = _.get(toSizes, platform, 0);
              const change = current - previous;

              const percentage = previous
                  ? `${change >= 0 ? "+" : ""}${_.round(change / previous * 100, 2)}%`
                  : current ? "+∞" : "+0.00%";

              const icon = _.cond([
                  [change => change < 0, _.constant("🔽")],
                  [change => change > 0, _.constant("🔼")],
                  [_.stubTrue, _.constant("🔄")]
              ])(change);

              return [
                  platform,
                  filesize(previous),
                  filesize(current),
                  `${change >= 0 ? "+" : ""}${filesize(Math.abs(change))} (${percentage})`,
                  icon
              ];
          };

          const rows = [
              ["OS/Platform", "Previous", "Current", "Change", "Trend"],
              ..._.map(platforms, platformRow)
          ];

          const output = `## 📦 App Size Analysis

          > [!NOTE]
          > Comparing \`${fromApp}\` ➔ \`${toApp}\`

          ### 📈 Size Comparison Table

          ${markdownTable(rows, { align: ["l", "c", "c", "c", "c"] })}`;

          core.setOutput("markdown", output);
