---
# yaml-language-server: $schema=https://json.schemastore.org/github-action.json
name: Application Inventory
description: Return a JSON array of app names from the apps directory

outputs:
  apps:
    description: Application Inventory
    value: ${{ steps.inventory.outputs.apps }}

runs:
  using: composite
  steps:
    - name: Application Inventory
      uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
      id: inventory
      with:
        script: |
          const fs = require('fs');
          const path = require('path');

          function scanDirectory(path) {
              try {
                  const entries = fs.readdirSync(path, { withFileTypes: true });
                  const folderNames = entries
                      .filter((entry) => entry.isDirectory())
                      .map((entry) => entry.name);
                  return folderNames;
              } catch (error) {
                  core.setFailed(`Error reading directory ${path}: ${error.message}`);
                  return [];
              }
          }

          const appsDirectory = path.resolve(process.cwd(), 'apps');
          const apps = scanDirectory(appsDirectory).sort();
          core.setOutput('apps', JSON.stringify(apps));
