---
# yaml-language-server: $schema=https://json.schemastore.org/github-action.json
name: App Versions
description: Takes an upstream version string and returns various version types

inputs:
  upstream-version:
    description: Upstream Version
    required: true

outputs:
  is-valid-semver:
    description: If version is valid semantic versioning
    value: ${{ steps.versions.outputs.is-valid-semver }}
  semantic:
    description: Semantic Version
    value: ${{ steps.versions.outputs.semantic }}
  raw:
    description: Raw Version
    value: ${{ steps.versions.outputs.raw }}
  upstream:
    description: Upstream Version
    value: ${{ steps.versions.outputs.upstream }}

runs:
  using: composite
  steps:
    - name: Create package.json
      shell: bash
      run: |-
        cat > package.json << 'EOF'
        {
          "dependencies": {
            "semver": "^7.7.2"
          }
        }
        EOF

    - name: Setup Node
      uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
      with:
        cache: npm
        cache-dependency-path: package.json
        node-version: 22.x

    - name: Setup Node Dependencies
      shell: bash
      run: |-
        npm install

    - name: App Versions
      uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
      id: versions
      env:
        UPSTREAM_VERSION: ${{ inputs.upstream-version }}
      with:
        script: |-
          const semver = require('semver');

          // Strip the v prefix and pre-release info
          function sanitize(version) {
              return version.replace(/^v/, '').split('-')[0];
          }

          function calver() {
              const now = new Date();
              return `${now.getFullYear()}.${now.getMonth() + 1}.${now.getDate()}`;
          }

          const upstreamVersion = process.env.UPSTREAM_VERSION;
          const strictSemverRegex = /^v?(\d+(\.\d+)?(\.\d+)?)/;

          const parsedVersion = strictSemverRegex.exec(upstreamVersion);
          const isValidSemver = parsedVersion !== null;
          const parsedSemver = isValidSemver ? semver.coerce(parsedVersion[0], {loose: true }) : null;
          const semanticVersion = isValidSemver ? `${parsedSemver.major}.${parsedSemver.minor}.${parsedSemver.patch}` : calver();
          const rawVersion = isValidSemver ? sanitize(upstreamVersion) : upstreamVersion;

          core.setOutput('is-valid-semver', isValidSemver);
          core.setOutput('semantic', semanticVersion);
          core.setOutput('raw', rawVersion);
          core.setOutput('upstream', upstreamVersion);
