---
# yaml-language-server: $schema=https://json.schemastore.org/github-action.json
name: App Exists
description: Return true or false if the app exists in the container registry

inputs:
  app:
    description: App Name
    required: true

outputs:
  exists:
    description: App Exists
    value: ${{ steps.app.outputs.exists }}

runs:
  using: composite
  steps:
    - name: App Exists
      uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
      id: app
      env:
        APP: ${{ inputs.app }}
      with:
        script: |-
          const app = process.env.APP;

          const { data: user } = await github.rest.users.getByUsername({
              username: context.repo.owner,
          });

          let pkg;
          if (user.type === 'Organization') {
              try {
                  const { data } = await github.rest.packages.getPackageForOrganization({
                      package_type: 'container',
                      package_name: app,
                      org: context.repo.owner,
                  });
                  pkg = data;
              } catch (error) {
                  if (error.status !== 404) {
                      throw error;
                  }
              }
          } else {
              try {
                  const { data } = await github.rest.packages.getPackageForUser({
                      package_type: 'container',
                      package_name: app,
                      username: context.repo.owner,
                  });
                  pkg = data;
              } catch (error) {
                  if (error.status !== 404) {
                      throw error;
                  }
              }
          }

          core.setOutput('exists', typeof pkg !== "undefined");
