---
name: "Lint"

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened

jobs:
  actionlint:
    name: actionlint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Get changed files
        id: changed-files
        uses: bjw-s-labs/action-changed-files@2cc35474e9d534ed0d743aa122fd142afbdaa0ad # v0.3.1
        with:
          patterns: |-
            .github/workflows/*.yaml
            .github/workflows/*.yml

      - name: Run actionlint
        if: steps.changed-files.outputs.changed_files != '[]'
        uses: bjw-s/action-actionlint@b346813e82708106544f48a93a5b3fbeeb8e37eb # v0.1.1
        with:
          actionlint_config: .ci/lint/actionlint.yml
          file_pattern: ${{ join(fromJSON(steps.changed-files.outputs.changed_files), ' ') }}

  yamllint:
    name: yamllint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Get changed files
        id: changed-files
        uses: bjw-s-labs/action-changed-files@2cc35474e9d534ed0d743aa122fd142afbdaa0ad # v0.3.1
        with:
          patterns: |-
            **/*.yaml
            **/*.yml

      - if: steps.changed-files.outputs.changed_files != '[]'
        name: Install yamllint
        shell: bash
        run: |
          pip install --user yamllint

      - if: steps.changed-files.outputs.changed_files != '[]'
        name: Run yamllint
        shell: bash
        run: |
          yamllint --config-file .ci/lint/yamllint.yaml --format github ${{ join(fromJSON(steps.changed-files.outputs.changed_files), ' ') }}

  lint_success:
    if: ${{ !cancelled() }}
    name: Linting success
    needs:
      - actionlint
      - yamllint
    runs-on: ubuntu-latest
    steps:
      - if: ${{ contains(needs.*.result, 'failure') }}
        name: Check matrix status
        run: exit 1
